version: '3.8'

services:
  backend:
    image: python:3.11
    container_name: poker_backend
    build:
      context: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - DB_NAME=pokerdb
      - DB_USER=postgres
      - DB_PASS=root
      - DB_HOST=db
      - DB_PORT=5432
    command: bash -c "pip install poetry && poetry install && poetry run fastapi run src/main.py"
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    image: node:20
    container_name: poker_frontend
    build:
      context: ./frontend
    working_dir: /app
    volumes:
      - ./frontend:/app  
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm run build && npm start"
    depends_on:
      - backend

  db:
    image: postgres:16.4-alpine3.20
    container_name: poker_db
    environment:
      POSTGRES_DB: pokerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
