version: '3.8'

services:
  backend:
    build: ./backend
    container_name: poker_backend
    environment:
      - DB_NAME=pokerdb
      - DB_USER=postgres
      - DB_PASS=root
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: poker_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
        

  db:
    image: postgres:16.4-alpine3.20
    container_name: poker_db
    environment:
      POSTGRES_DB: pokerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
